-- CREATE SCHEMA scilit_db;

-- SELECT VERSION();

DROP TABLE IF EXISTS publication_authors;
DROP TABLE IF EXISTS publications;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS sources;
DROP TABLE IF EXISTS dates;

